# Generated by Django 5.1.7 on 2025-11-03 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_selection_type', models.BooleanField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data_source', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'formats',
                'indexes': [models.Index(fields=['name'], name='idx_formats_name')],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'markets',
                'indexes': [models.Index(fields=['name'], name='idx_market_name')],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'representatives',
                'indexes': [models.Index(fields=['name'], name='idx_representatives_name')],
            },
        ),
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('station_group', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assign_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_stations', to='accounts.user')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_stations', to='admin_panel.format')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_stations', to='admin_panel.market')),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_stations', to='admin_panel.representative')),
            ],
            options={
                'db_table': 'radio_stations',
                'indexes': [models.Index(fields=['assign_user'], name='idx_radio_stations_assign_user'), models.Index(fields=['market'], name='idx_radio_stations_market'), models.Index(fields=['rep'], name='idx_radio_stations_rep'), models.Index(fields=['format'], name='idx_radio_stations_format')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_radio_station_name')],
            },
        ),
    ]
