# Generated by Django 5.1.7 on 2025-11-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
