# Generated by Django 5.1.7 on 2025-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_radiostation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
