# Generated by Django 5.1.7 on 2025-11-08 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
        ('admin_panel', '0003_alter_radiostation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date_selection_type', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('early_payment_discount', models.BooleanField(default=False)),
                ('goal_cpm', models.FloatField(blank=True, null=True)),
                ('additional_daypart_uuid', models.TextField(blank=True, null=True)),
                ('additional_length', models.IntegerField(blank=True, null=True)),
                ('additional_spots_per_week', models.IntegerField(blank=True, null=True)),
                ('additional_product', models.TextField(blank=True, null=True)),
                ('no_count_weeks', models.FloatField(blank=True, null=True)),
                ('no_discount_amount', models.FloatField(blank=True, null=True)),
                ('total_spots_per_week', models.IntegerField(blank=True, null=True)),
                ('total_spots', models.IntegerField(blank=True, null=True)),
                ('final_total', models.FloatField(blank=True, null=True)),
                ('total_aqh', models.FloatField(blank=True, null=True)),
                ('total_cpm', models.FloatField(blank=True, null=True)),
                ('total_nc_discount', models.FloatField(blank=True, null=True)),
                ('total_epd_discount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_status', models.TextField(default='Draft')),
                ('partially_filled', models.BooleanField(blank=True, null=True)),
                ('schedule_cpm', models.FloatField(blank=True, null=True)),
                ('toggle_button_status', models.BooleanField(blank=True, null=True)),
                ('epd_cpm', models.FloatField(blank=True, null=True)),
                ('user_draft', models.JSONField(blank=True, null=True)),
                ('additional_day_specific', models.BooleanField(default=False)),
                ('target_radio_station', models.ForeignKey(db_column='target_radio_station', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_panel.radiostation')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_for_user', to='accounts.user')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
