# Generated by Django 5.1.7 on 2025-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_schedule'),
    ]

    operations = [

         migrations.RunSQL(
            sql="""
            ALTER TABLE `schedules`
            MODIFY COLUMN `schedule_status` 
              ENUM(
                'PENDING_STATION',
                'PENDING_ADMIN',
                'APPROVED',
                'DECLINED_ADMIN',
                'DECLINED_STATION',
                'DRAFT',
                'COMPLETED'
              ) NOT NULL DEFAULT 'DRAFT';
            """,
            reverse_sql="""
            ALTER TABLE `schedules`
            MODIFY COLUMN `schedule_status` TEXT;
            """
        ),
      
    ]
