# Generated by Django 5.2.7 on 2025-11-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_schedule_schedule_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_status',
            field=models.TextField(default='Draft'),
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='admin_panel.campaign')),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, to='admin_panel.schedule')),
            ],
            options={
                'db_table': 'campaign_schedules',
                'unique_together': {('campaign', 'schedule')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedules',
            field=models.ManyToManyField(related_name='campaigns', through='admin_panel.CampaignSchedule', to='admin_panel.schedule'),
        ),
    ]
