# Generated by Django 5.1.7 on 2025-12-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=False, null=False, unique=True),
            preserve_default=False,
        ),
    ]
