# Generated by Django 5.2.7 on 2025-12-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default='defaultds', unique=True),
            preserve_default=False,
        ),
    ]
