# Generated by Django 5.2.7 on 2025-12-15 10:15

import uuid
from django.db import migrations, models



def seed_products(apps, schema_editor):
    Product = apps.get_model("admin_panel", "Product")

    Product.objects.bulk_create(
        [
            Product(
                uuid=uuid.UUID("13127247-e9f5-44e4-bff9-88ecb0182cd5"),
                product_name="WKND",
                day_specific=False,
                length=60,
                sort_order=7,
            ),
            Product(
                uuid=uuid.UUID("571ad6ad-d5b4-42c0-a898-e4f8dbcbd674"),
                product_name="AMD2",
                day_specific=False,
                length=60,
                sort_order=3,
            ),
            Product(
                uuid=uuid.UUID("57a7139d-d97c-40d7-8e66-781ac964f468"),
                product_name="AMD1",
                day_specific=False,
                length=60,
                sort_order=2,
            ),
            Product(
                uuid=uuid.UUID("61b5c62c-d625-47f2-bed8-e125444785cb"),
                product_name="PORT",
                day_specific=False,
                length=60,
                sort_order=8,
            ),
            Product(
                uuid=uuid.UUID("67457ca9-c776-4240-a1f2-a97ca39aa54e"),
                product_name="WKDAY",
                day_specific=False,
                length=60,
                sort_order=1,
            ),
            Product(
                uuid=uuid.UUID("c52d6759-2ed1-42e6-9a4e-451557bf0bb9"),
                product_name="PMD1",
                day_specific=False,
                length=60,
                sort_order=4,
            ),
            Product(
                uuid=uuid.UUID("db69670a-a098-474c-af12-73b712c0ed99"),
                product_name="PMD2",
                day_specific=False,
                length=60,
                sort_order=5,
            ),
            Product(
                uuid=uuid.UUID("d9b99839-0455-4b08-b6d3-063b83e87bed"),
                product_name="EXT1",
                day_specific=False,
                length=60,
                sort_order=6,
            ),
        ],
        ignore_conflicts=False, 
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_schedule_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=False)),
                ('product_name', models.TextField()),
                ('day_specific', models.BooleanField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('historical_rate', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('aqh', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.RunPython(seed_products)
    ]
