# Generated by Django 6.0 on 2025-12-17 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models



def daypart_seeeding():
    dayparts=['WF 6a-10p','AD 6a-6p','DE 3a-5p','AMD1 6p-10p' ,'AMD2 10p-12a']
    # ProductDayPart = apps.get_model("admin_panel", "ProductDayPart")
    Product = app.get_model('admin_panel', 'Product')
    for product in Product.objects.all():
        for daypart in dayparts:
            ProductDayPart.objects.get_or_create(
                product=product,
                daypart=daypart,
            )
    

def seed_product_day_parts(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductDayPart = apps.get_model('products', 'ProductDayPart')

    DAY_PARTS = [
        "Morning Drive",
        "Midday",
        "Evening Drive",
    ]

    for product in Product.objects.all():
        for daypart in DAY_PARTS:
            # Prevent duplicates if migration is re-run
            ProductDayPart.objects.get_or_create(
                product=product,
                daypart=daypart,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ProductDayPart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daypart', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_parts', to='admin_panel.product')),
            ],
            options={
                'db_table': 'product_day_parts',
                'indexes': [models.Index(fields=['product'], name='idx_product_day_parts_product_id'), models.Index(fields=['daypart'], name='product_day_parts_daypart_idx')],
            },
        ),
        migrations.RunPython(seed_product_day_parts),
    ]
